### ISSUE TITLE
Misleading (error-yielding) warning in test_icr

### ISSUE THREAD

**Issue by MarHai** [joon-e/tidycomm#14]
Running `test_icr` with codings from three coders where no case has codings from all three coders yields a warning (consider setting `na.omit = TRUE`). However, when following this suggestion, the function fails with a hard error (as one of the then-vectors is NULL).

Code to replicate:
```r
data <- tibble(
  unit = c(1, 1, 2, 2, 3, 3),
  coder = c('a', 'b', 'a', 'c', 'b', 'c'),
  code = rnorm(6)
)

data %>% test_icr(unit, coder)
data %>% test_icr(unit, coder, na.omit = T)
```

**Comment by joon-e** [comment]
This is expected behavior, as the units-coders matrix used for ICR calculations has the assumption that all units were coded by the same coders. So if the actual coder is to be neglected in the calculation and it only matters that one unit was coded at least x times, but not by whom it was coded, the `coder_var` should not be `coder`, but a variable indicating the _coding_:

```r
data %>% 
  group_by(unit) %>% 
  mutate(coding = 1:n()) %>%
  test_icr(unit, coding, code)
```

However, I concur this should result in a more descriptive error and be pointed out in the docs.
