### ISSUE TITLE
[Feature Request] Converting factors to numeric in add_index

### ISSUE THREAD

**Issue by Kudusch** [joon-e/tidycomm#16]
When calculating an index for factorial columns, `rowSums` and `rowMeans` will throw an error because the input is not numeric. There are situations where one might want to calculate an index for factorial columns without changing them to numeric beforehand and lose the factor levels, e.g. for Likert-type scales.

Adding an option to cast the input data to numeric might help with situations like that. 

```
list_labels <- c("strongly agree", "agree", "undecided", "disagree", "strongly disagree")
df <- data.frame(
  a = sample(1:5, 100, replace = TRUE),
  b = sample(1:5, 100, replace = TRUE),
  c = sample(1:5, 100, replace = TRUE)
)
df$a <- factor(df$a, levels = 1:5, labels = list_labels)
df$b <- factor(df$b, levels = 1:5, labels = list_labels)
df$c <- factor(df$c, levels = 1:5, labels = list_labels)

df %>% 
  add_index(
    i,
    a,
    b,
    c,
    type = "mean",
    cast.numeric = TRUE
  )
```

If that's a feature that fits the package, I could implement this and make a pull request. The implementation would simply be this piece of code in the `add_index` function (and corresponding documentation):

```
if (cast.numeric) {
    i <- i %>% mutate(across(everything(), as.numeric))
  }
```

**Comment by joon-e** [comment]
Sorry for the late response, I am bit flooded by work at the moment and thus haven't been able to work on this package quite some time. I think the feature is a good idea, so I'd like to get this implemented. 

For ease of use reasons, I think this should include some more specific error messages, i.e. indiciating which (if any) `...` variables are not numeric, and if they are factors, suggest using `cast.numeric = TRUE`. If this is possible for you to include in a pull request, please go ahead, otherwise I'll add it to my list of changes that I will hopefully get to in June.
